version: '3.8'

services:
  dolt-sql-server:
    image: dolthub/dolt-sql-server:latest
    ports:
      - "3307:3307"
    volumes:
      # Mount the server directory with a single .yaml config
      - ./servercfg:/etc/dolt/servercfg.d
      # Passthrough the database directory so that it can be used in the container
      - ./databases:/var/lib/dolt
    restart: unless-stopped
